config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
  }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', method: :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'styleguide' => 'static_pages#style_guide'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  resources :users, only: [:show, :update]

  namespace :users do
    resources :tracks, only: :create
  end
  get 'dashboard' => 'users#show', as: :dashboard

  # Deprecated Route to Introduction to Web Development from external links
  get '/courses/introduction-to-web-development' => redirect('/courses/web-development-101')

  resources :courses, only: %i(index show) do
    resources :lessons, only: :show
  end

  resources :lessons, only: :show do
    resources :projects, only: %i(index create update destroy) do
      resources :votes, only: %i(create)
      delete 'vote', to: 'votes#destroy'
    end

    resources :lesson_completions, only: %i(create), as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', :as => 'lesson_completions'
  end

  resources :reports, only: :create

  match '/404' => 'errors#not_found', via: [ :get, :post, :patch, :delete ]

  # Explicitly redirect deprecated routes (301)
  get '/courses/curriculum' => redirect('/courses')
  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')

  resources :tracks, only: [:index, :show]
end

app/views/shared/_admin_flash.html.erb
<div class="container">
  <% AdminFlash.showable_messages(disabled_flash_ids_from_cookies).each do |admin_flash|  %>
    <div class="alert alert-success fade show admin-flash">
      <button class="close "data-expire="<%= admin_flash.expires %>" data-id="<%= admin_flash.id %>" data-dismiss="alert">&times;</button>
      <%= admin_flash.message.html_safe %>
    </div>
  <% end %>
</div>

app/views/shared/_bottom_cta.html.erb
<div class="bottom-cta">
  <p class="bottom-cta__heading"><%= heading %></p>

  <p class="bottom-cta__sub-heading"><%= sub_heading %></p>
  <%= button %>
</div>

app/views/shared/_fb.html.erb
<% if Rails.env.production? && current_page?(root_path) %>
<!-- FB pixel -->
<script>
    !function(f,b,e,v,n,t,s)
    {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
    n.callMethod.apply(n,arguments):n.queue.push(arguments)};
    if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
    n.queue=[];t=b.createElement(e);t.async=!0;
    t.src=v;s=b.getElementsByTagName(e)[0];
    s.parentNode.insertBefore(t,s)}(window,document,'script',
    'https://connect.facebook.net/en_US/fbevents.js');
    fbq('init', '204929933721168'); 
    fbq('track', 'PageView');
</script>
<noscript>
    <img height="1" width="1" src="https://www.facebook.com/tr?id=204929933721168&ev=PageView&noscript=1"/>
</noscript>
<% end %>

app/views/shared/_flash_helper.html.erb
<% flash.each do |type, message| %>
  <div class='alert <%= bootstrap_class_for(type) %> fade show'>
    <button class='close' data-dismiss='alert'>&times;</button>
    <%= message.html_safe %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<div class="container">
  <%= render 'shared/flash_helper', flash: flash %>
</div>

app/views/shared/_ga.html.erb
<!-- Google Analytics Tracking Snippet -->
<!-- Only load it if we're in a production environment! -->
  
  
<% if Rails.env.production? %>

  <script type="text/javascript">  
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-41005438-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>

<% else %>

  <script type="text/javascript">
    var _gaq = [];
  </script>

<% end %>

app/views/shared/_head.html.erb
<head>
<!--
    .
  .o8
.odin8o  .odino.  oo.ooooo.
  888   d88' `88b  888' `88b
  888   888   888  888   888
  888 . 888   888  888   888
  "888" `Y8odinP'  888bod8P'
                   888
                  odin!


Our full stack curriculum is free and supported by a passionate open source community. Do you want to contribute? Chat with us at https://discord.gg/hvqVr6d
-->

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="The Odin Project empowers aspiring web developers to learn together">
  <meta name="keywords" content="learn web development, learn ruby on rails, ruby on rails, ruby, rails">
  <meta property="og:image" content="<%= image_url('og-logo.png') %>">

  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
  <link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="/manifest.json">
  <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
  <title>
    <%= content_for(:title) || 'Your Career in Web Development Starts Here | The Odin Project' %>
  </title>

  <%= stylesheet_link_tag 'application', media: 'all'%>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic|Open+Sans:300,300italic,400,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

app/views/shared/_logo.html.erb
<%= link_to home_url, class: 'logo' do %>
  <%= image_tag 'odin-logo.svg', class: 'logo__img' %>
  <div class="logo__text"> The Odin Project </div>
<% end %>

app/views/shared/_navbar.html.erb
<%= render 'shared/navbar_modal' %>

<div class="navbar navbar-expand-md navbar-light">
  <div class="navbar-brand">
    <%= render 'shared/logo' %>
  </div>

  <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="modal" data-target="#navbar-supported-content" aria-controls="navbar-supported-content" aria-expanded="false" aria-label="toggle-navigation">
    <span class="navbar-toggler-icon open"></span>
    <span class="sr-only">Open navigation</span>
  </button>

  <% if user_signed_in? %>
    <nav class="collapse navbar-collapse">
      <!-- Full Width Navbar -->
      <ul class="navbar-nav ml-auto hidden-md-down">
        <li class="nav-item <%= active_class(courses_path) %>">
          <%= link_to 'My courses', track_path(current_user.track_id, ref: 'homenav'), class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown js-dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Community
          </a>
          <ul class="dropdown-menu dropdown-menu-right menu-options pb-0">
            <li>
              <%= link_to forum_link, class: 'drop-down-link accent', target: '_blank', rel: 'noreferrer' do %>
                <span class="drop-down-logo fas fa-users mt-2"></span>Forum
              <% end %>
            </li>
            <li>
              <%= link_to chat_link, class: 'drop-down-link accent', target: '_blank', rel: 'noreferrer' do %>
                <span class="drop-down-logo fas fa-comment mt-2"></span>Chat
              <% end %>
            </li>
          </ul>
        </li>

        <li class="divider nav-link">|</li>
        <%= render 'shared/user_dropdown' %>
      </ul>
  <% else %>
    <nav class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item <%= active_class(courses_path) %>">
          <%= link_to 'Curriculum', tracks_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown js-dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Community
          </a>
          <ul class="dropdown-menu dropdown-menu-right menu-options pb-0">
            <li>
              <%= link_to forum_link, class: "drop-down-link accent", target: '_blank', rel: 'noreferrer' do %>
                <span class="drop-down-logo fas fa-users mt-2"></span>Forum
              <% end %>
            </li>
            <li>
              <%= link_to chat_link, class: 'drop-down-link accent', target: '_blank', rel: 'noreferrer' do %>
                <span class="drop-down-logo fas fa-comment mt-2"></span>Chat
              <% end %>
            </li>
          </ul>
        </li>
        <li class="nav-item <%= active_class(about_path) %>">
          <%= link_to 'About', about_path(ref: 'homenav'), class: 'nav-link' %>
        </li>
        <li class="nav-item <%= active_class(faq_path) %>">
          <%= link_to "FAQ", faq_path(ref: 'homehav'), class: 'nav-link' %>
        </li>

        <li class="divider nav-link">|</li>

        <li class="nav-item <%= active_class(sign_up_path) %>">
          <%= link_to 'Sign Up', sign_up_path(ref: 'homenav'), class: 'nav-link' %>
        </li>
        <li class="nav-item <%= active_class(login_path) %>">
          <%= link_to 'Log In', login_path(ref: 'homenav'), class: 'nav-link' %>
        </li>
      </ul>
    </nav>
  <% end %>
    </ul>
  </nav>
</div>

app/views/shared/_navbar_and_flashes.html.erb
<%= render 'shared/navbar' %>

<div class="nav-spacer"></div>

<%= render 'shared/admin_flash'%>

<%= render "layouts/#{flash[:partial]}" if flash[:partial] %>

<%= render 'shared/flashes', flash: flash unless flash.empty? %>

app/views/shared/_navbar_modal.html.erb
<div id="navbar-supported-content" class="modal modal-fullscreen-menu fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <div class="navbar-brand">
          <%= render 'shared/logo' %>
        </div>
        <button aria-label="Close" type="button" class="close" data-dismiss="modal">
          <span class="sr-only">Close navigation</span>
          <span class="close-icon">&times;</span>
        </button>
      </div>
      <ul class="modal-links">
        <% if user_signed_in? %>
          <li class="nav-item <%= active_class(dashboard_path) %>">
            <%= link_to 'Dashboard', dashboard_path(ref: 'homenav'), class: 'nav-link' %>
          </li>

          <li class="nav-item <%= active_class(courses_path) %>">
            <%= link_to 'Curriculum', track_path(current_user.track_id), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Forum', forum_link, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Chat', chat_link, class: 'nav-link gitter-chat-link', target: '_blank', rel: 'noreferrer' %>
          </li>

          <div class="dropdown-divider"></div>
          <li class="nav-item <%= active_class(edit_user_registration_path) %>">
            <%= link_to "Settings", edit_user_registration_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <%= link_to "Log Out", logout_path(ref: 'homenav'), class: 'nav-link' %>
          </li>

        <% else %>
          <li class="nav-item <%= active_class(courses_path) %>">
            <%= link_to 'Curriculum', tracks_path, class: 'nav-link' %>
          </li>

          <li class="nav-item">
            <a class="nav-link dropdown-toggle" data-toggle="collapse" href="#collapseCommunity" role="button" aria-expanded="false" aria-controls="collapseCommunity">
              Community
            </a>
            <div class="collapse" id="collapseCommunity">
              <%= link_to 'Forum', forum_link, class: 'nav-link' %>
              <%= link_to 'Chat', chat_link, class: 'nav-link gitter-chat-link', target: '_blank', rel: 'noreferrer' %>
            </div>
          </li>

          <li class="nav-item <%= active_class(about_path) %>">
            <%= link_to 'About', about_path(ref: 'homenav'), class: 'nav-link' %>
          </li>

          <li class="nav-item <%= active_class(faq_path) %>">
            <%= link_to "FAQ", faq_path(ref: 'homehav'), class: 'nav-link' %>
          </li>

          <div class="dropdown-divider"></div>

          <li class="nav-item <%= active_class(sign_up_path) %>">
            <%= link_to 'Sign Up', sign_up_path(ref: 'homenav'), class: 'nav-link' %>
          </li>
          <li class="nav-item <%= active_class(login_path) %>">
            <%= link_to 'Log In', login_path(ref: 'homenav'), class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_omniauth_buttons.html.erb
<% resource_class.omniauth_providers.each do |provider| %>
  <%= button_to omniauth_authorize_path(resource_name, provider), class: "button button--#{provider} oauth-button full-width push-down" do %>
    <i class="fab fa-<%= provider%> providers-icon"></i>
    <%= provider.to_s.titleize %>
  <% end %>
<% end %>

app/views/shared/_sidecar.html.erb
<div class="floating-dropdown">
  <div class="floating-dropdown__item floating-dropdown--hidden-item text-center" data-toggle='tooltip' data-placement='left' title='Chat'>
    <%= link_to chat_link, target: :_blank, rel: 'noreferrer' do %>
      <i class="fas fa-comment"></i>
    <% end %>
  </div>
  <div class="floating-dropdown__item floating-dropdown--hidden-item text-center" data-toggle='tooltip' data-placement='left' title='Forum'>
    <%= link_to forum_link, target: :_blank, rel: 'noreferrer' do %>
      <i class="fas fa-users" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class="floating-dropdown__item main-floating-btn">
    <i class="fas fa-comments" aria-hidden="true"></i>
  </div>
</div>

app/views/shared/_user_dropdown.html.erb
<div class="dropdown js-dropdown">
  <button class="avatar" aria-label="User Menu" style="background-image:url(<%= avatar_path(current_user.avatar) %>)" data-toggle="dropdown"></button>
  <ul class="dropdown-menu menu-options">
    <li id="dash-active">
      <%= link_to dashboard_path, class: "drop-down-link accent #{active_class(dashboard_path)}" do %>
        <span class="drop-down-logo dashboard-logo"></span>Dashboard
      <% end %>
    </li>
    <li>
      <%= link_to edit_user_registration_path, class: "drop-down-link accent #{active_class(edit_user_registration_path)}" do %>
        <span class="drop-down-logo settings-logo"></span>Settings
      <% end %>
    </li>
    <li>
      <%= link_to logout_path(ref: 'homenav'), class: 'drop-down-link accent' do %>
        <span class="drop-down-logo logout-logo"></span>Log out
      <% end %>
    </li>
  </ul>
</div>