config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
  }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', method: :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'styleguide' => 'static_pages#style_guide'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  resources :users, only: [:show, :update]

  namespace :users do
    resources :tracks, only: :create
  end
  get 'dashboard' => 'users#show', as: :dashboard

  # Deprecated Route to Introduction to Web Development from external links
  get '/courses/introduction-to-web-development' => redirect('/courses/web-development-101')

  resources :courses, only: %i(index show) do
    resources :lessons, only: :show
  end

  resources :lessons, only: :show do
    resources :projects, only: %i(index create update destroy) do
      resources :votes, only: %i(create)
      delete 'vote', to: 'votes#destroy'
    end

    resources :lesson_completions, only: %i(create), as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', :as => 'lesson_completions'
  end

  resources :reports, only: :create

  match '/404' => 'errors#not_found', via: [ :get, :post, :patch, :delete ]

  # Explicitly redirect deprecated routes (301)
  get '/courses/curriculum' => redirect('/courses')
  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')

  resources :tracks, only: [:index, :show]
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  acts_as_votable
  paginates_per 100

  validates :repo_url, format: { with: /\Ahttps?:\/\/github.com\//,
    message: 'must start with http://github.com/ or https://github.com/' }

  default_scope { order('updated_at desc') }
  scope :all_submissions, ->(lesson_id) { where(lesson_id: lesson_id) }

  def upvote_for(user)
    vote_by(voter: user)
  end

  def remove_vote_for(user)
    unliked_by(user)
  end

  def total_votes
    votes_for.count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_request, except: :index
  before_action :find_lesson
  before_action :find_project, only: %i(update destroy)

  authorize_resource only: %i(update destroy)

  def index
    @projects = all_projects.page(params[:page]).per(50)
    @course = CourseDecorator.new(@lesson.course)
    @user = current_user
    @project = @projects.where(user_id: current_user.id).first if current_user
  end

  def create
    @project = new_project(project_params)
    @project.save
    @projects = latest_projects
  end

  def update
    @project.update(project_params)
    @decorated_project = ProjectDecorator.new(@project)
  end

  def destroy
    @project.destroy
    @project = new_project
    @projects = latest_projects
  end

  private

  def all_projects
    Project.all_submissions(@lesson.id).order(updated_at: :desc)
  end

  def new_project(parameters = {})
    current_user.projects.new(parameters).tap do |project|
      project.lesson_id = @lesson.id
    end
  end

  def latest_projects
    all_projects.limit(10)
  end

  def find_project
    @project = Project.find(params[:id])
  end

  def find_lesson
    @lesson = LessonDecorator.new(lesson)
  end

  def lesson
    Lesson.friendly.find(params[:lesson_id])
  end

  def project_params
    params.require(:project).permit(:repo_url, :live_preview)
  end

  def authenticate_request
    return head :unauthorized unless user_signed_in?
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def heart_icon_or_button_for(user, project)
    HeartIconPresenter.render(user: user, project: project, view: self)
  end
end

app/views/projects/_delete_project_modal.html.erb
<div class="modal modal-main fade"
  id="delete-project-modal"
  tabindex="-1"
  role="dialog"
  aria-labelledby="projectSubmissionDeleteModal"
  aria-hidden="true"
  data-backdrop="static"
  data-keyboard="false"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-main__header">
        <button type="button" class="close modal-main__close-icon" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <div class="delete-project-form text-center">
          <h1 class="delete-project-form__title accent">Delete project</h1>
          <p class="text-center">
            Are you sure you want to delete the project submission?
          </p>

          <div class="delete-project-form__actions">
            <%= link_to [lesson, project],
              class: 'button btn-danger',
              method: :delete,
              remote: true do %>
              <i class="fas fa-trash"></i>&nbsp;Yes, delete it
            <% end %>

            <%= button_tag 'No, I changed my mind',
              type: 'button',
              class: 'button',
              data: { dismiss: 'modal' }
            %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/projects/_form.html.erb
<div class="card-main card-main--shadowless project-form">
  <h1 class="text-center project-form__title accent">Upload your project</h1>

  <%= form_for [lesson, project], remote: true, class: 'form' do |form| %>
    <div class="form__section">
      <span class="fab fa-github form__icon"></span>
      <%= form.text_field :repo_url,
        class: 'form__element form__element--with-icon',
        placeholder: 'Repository URL'
      %>
    </div>

    <% if lesson.has_live_preview? %>
      <div class="form__section">
        <span class="fas fa-paperclip form__icon"></span>
        <%= form.text_field :live_preview,
          class: 'form__element form__element--with-icon',
          placeholder: 'Live Preview URL'
        %>
      </div>
    <% end %>

    <div class="form__section text-center">
      <%= form.submit (project.new_record? ? 'Upload project' : 'Update project'),
        class: 'button button--primary project-form__button project-form__submit-btn',
        disable_with: (project.new_record? ? 'Uploading project...' : 'Updating project..')
      %>
    </div>

    <div class="form__section text-center">
      <%= button_tag 'Cancel',
        type: 'button',
        class: 'button project-form__button',
        data: { dismiss: 'modal' }
      %>
    </div>

    <% if project.persisted? %>
      <div class="form__section text-center">
        <%= button_tag 'Delete',
          type: 'button',
          class: 'button project-form__button btn-danger',
          data: { toggle: 'modal', target: '#delete-project-modal' }
        %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/projects/_form_modal.html.erb
<div class="modal modal-main fade"
  id="project-submission-modal"
  tabindex="-1"
  role="dialog"
  data-backdrop="static"
  aria-labelledby="projectSubmissionModal"
  aria-hidden="true"
  data-keyboard="false"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-main__header">
        <button type="button" class="close modal-main__close-icon" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= render 'projects/form', lesson: lesson, project: project %>
      </div>
    </div>
  </div>
</div>

app/views/projects/_owner_name_and_report_link.html.erb
<% if project.user == current_user %>
  <%= link_to '#', data: { toggle: 'modal', target: '#project-submission-modal'} do %>
    <%= project.owner_name.capitalize %>
  <% end %>
<% else %>
  <% if user_signed_in? %>
    <%= link_to '#',
      class: 'project__report-link',
      title: 'Report project',
      data: {
        'toggle' => 'modal',
        'target' => '#project-report-modal',
        'project-id' => project.id,
      } do %>
        <i class="fas fa-exclamation-circle" aria-hidden="true"></i>
      <% end %>
    <% end %>

  <%= project.owner_name.capitalize %>
<% end %>

app/views/projects/_project.html.erb
<div class="row project">
  <div class="col-5 col-sm-3 col-md-2 col-lg-3 project__votes">
    <%= heart_icon_or_button_for(current_user, project) %>

    <span class="project__votes-count">
     <%= project.total_votes %>
    </span>
  </div>

  <div class="col-7 col-sm-9 col-md-3 col-lg-3 project__owner-name bold">
    <%= render 'projects/owner_name_and_report_link', project: project %>
  </div>

  <div class="col-md-7 col-lg-6 project__buttons">
    <%= link_to 'View Code', project.repo_url, class: 'button project__button', target: '_blank' %>

    <% if project.live_preview.present? %>
      <%= link_to 'Live Preview', project.live_preview, class: 'button project__button live-preview-button', target: '_blank' %>
    <% end %>
  </div>
</div>

app/views/projects/_project_submission.html.erb
<div class="row project project--borderless align-items-center">
  <div class="col-md-5 lesson-title-wrapper">
    <p class="bold"><%= project.lesson.title %></p>
  </div>

  <div class="col-md-7 project__buttons">
    <%= link_to 'View Code', project.repo_url, class: 'button project__button', target: '_blank' %>

    <% if project.live_preview.present? %>
      <%= link_to 'Live Preview', project.live_preview, class: 'button project__button live-preview-button', target: '_blank' %>
    <% end %>
  </div>
</div>

app/views/projects/_report_form.html.erb
<div class="card-main card-main--shadowless report-project-form">
  <div class="col-12">
    <h1 class="text-center">Report project</h1>

    <%= form_tag reports_path, remote: true, class: 'form' do %>
      <%= hidden_field_tag :project_id %>

      <div class="form__section">
        <%= label_tag :description %>
        <%= text_area_tag :description,
          nil,
          required: true,
          class: 'form__element report-project-form__description',
          placeholder: 'Tell us why you think we should flag the submission'
        %>
      </div>

      <div class="text-center">
        <%= submit_tag 'Report project',
          class: 'button button--primary report-project-form__report-button'
        %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/_report_form_modal.html.erb
<div class="modal modal-main fade"
  id="project-report-modal"
  tabindex="-1"
  role="dialog"
  data-backdrop="true"
  aria-labelledby="projectReportModal"
  aria-hidden="true"
>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header modal-main__header">
        <button type="button" class="close modal-main__close-icon" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= render 'projects/report_form', lesson: @lesson %>
      </div>
    </div>
  </div>
</div>

app/views/projects/create.js.erb
<% if @project.persisted? %>
  $('#project-submission-modal').modal('hide');
  $('.modal-backdrop').remove();
  toastr.success('Your submission was added', 'Success!');
  $('#add-submission-button').remove();

  $('#submissions')
    .html("<%= j render 'lessons/recent_submissions', projects: @projects, project: @project, lesson: @lesson %>");
  $('#project-submission-modal-wrapper')
    .html("<%= j render 'form_modal', lesson: @lesson, project: @project %>");
  $('body')
    .prepend("<%= j render 'projects/delete_project_modal', lesson: @lesson, project: @project %>");

<% else %>
  toastr.error('<%= @project.errors.full_messages[0] %>', 'Error', {
    closeButton: 'true',
    tapToDismiss: false,
  });
<% end %>

app/views/projects/destroy.js.erb
$('#delete-project-modal').remove();
$('.modal-backdrop').remove();
$('#project-submission-modal').remove();
toastr.success('Your submission was deleted', 'Success!');

if ($('#index-submissions').length === 0) {
  $('#submissions').html("<%= j render 'lessons/recent_submissions', projects: @projects, project: @project, lesson: @lesson %>");
  $('#project-submission-modal-wrapper').html("<%= j render 'projects/form_modal', lesson: @lesson, project: @project %>");
} else {
  $('#index-submissions').html("<%= j render 'lessons/index_submissions', projects: @projects %>");
}

app/views/projects/index.html.erb
<%= title("#{@lesson.title} Submissions") %>

<% if user_signed_in? %>
  <%= render 'projects/report_form_modal', lesson: @lesson %>
<% end %>

<% if user_signed_in? && @project %>
  <div id="project-submission-modal-wrapper">
    <%= render 'projects/form_modal', lesson: @lesson, project: @project %>
  </div>
  <%= render 'projects/delete_project_modal', lesson: @lesson, project: @project %>
<% end %>

<div class="gradient">
  <div class="container">
    <div class="projects-header">
      <%= render 'courses/course/banner', course: @course %>
      <h2 class="projects-header__title accent"><%= "All Submissions - #{@lesson.title}"%></h2>
    </div>

    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <div id="index-submissions" class="card-main">
          <% if @lesson.has_submission? %>
            <%= render 'lessons/index_submissions', projects: @projects %>
            <%= paginate @projects %>
          <% else %>
            <h4 class="text-center accent">
              This project does not accept submissions
            </h4>
          <% end %>
        </div>
      </div>
    </div>

    <%= render 'shared/bottom_cta',
      heading: 'Have a question?',
      sub_heading: 'Chat with our friendly Odin community in our Discord chatrooms!',
      button: chat_button
    %>
  </div>
</div>

app/views/projects/update.js.erb
<% if @project.valid? %>
  $('#project-submission-modal').modal('hide');
  $('.modal-backdrop').remove();
  toastr.success('Your project submission was updated!', 'Success');

  $('#project-<%= @decorated_project.id %>')
    .html("<%= j render 'projects/project', project: @decorated_project %>");

<% else %>
  toastr.error('<%= @decorated_project.errors.full_messages[0] %>', 'Error', {
    closeButton: true,
    tapToDismiss: false,
  });
<% end %>