config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
  }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', method: :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'styleguide' => 'static_pages#style_guide'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  resources :users, only: [:show, :update]

  namespace :users do
    resources :tracks, only: :create
  end
  get 'dashboard' => 'users#show', as: :dashboard

  # Deprecated Route to Introduction to Web Development from external links
  get '/courses/introduction-to-web-development' => redirect('/courses/web-development-101')

  resources :courses, only: %i(index show) do
    resources :lessons, only: :show
  end

  resources :lessons, only: :show do
    resources :projects, only: %i(index create update destroy) do
      resources :votes, only: %i(create)
      delete 'vote', to: 'votes#destroy'
    end

    resources :lesson_completions, only: %i(create), as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', :as => 'lesson_completions'
  end

  resources :reports, only: :create

  match '/404' => 'errors#not_found', via: [ :get, :post, :patch, :delete ]

  # Explicitly redirect deprecated routes (301)
  get '/courses/curriculum' => redirect('/courses')
  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')

  resources :tracks, only: [:index, :show]
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  extend FriendlyId

  friendly_id :slug_candidates, use: [:slugged, :finders]

  belongs_to :section
  has_one :course, through: :section
  has_many :projects
  has_many :lesson_completions, dependent: :destroy
  has_many :completing_users, through: :lesson_completions, source: :student

  validates :position, presence: true

  def self.projects_without_submissions
    [
      'Installations',
      'Practicing Git Basics',
      'Building Your Resume'
    ]
  end

  def type
    is_project? ? 'Project' : 'Lesson'
  end

  def position_in_section
    section_lessons.where('position <= ?', position).count
  end

  def import_content_from_github
    LessonContentImporter.for(self)
  end

  def has_submission?
    is_project? &&
    accepts_submission? &&
    is_not_a_ruby_project? # should be removed after revamping ruby lessons
  end

  def has_live_preview?
    has_submission? && is_not_a_ruby_project?
  end

  private

  def section_lessons
    section.lessons
  end

  def slug_candidates
    [
      :title,
      [:title, course_title]
    ]
  end

  def course_title
    course&.title
  end

  def accepts_submission?
    !Lesson.projects_without_submissions.include?(title)
  end

  def is_not_a_ruby_project?
    title != 'Ruby' && course_title != 'Ruby Programming'
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_user

  def show
    @lesson = decorated_lesson
    set_project_and_submissions if @lesson.has_submission?
  end

  private

  def set_user
    if user_signed_in?
      @user = User.includes(:completed_lessons).find(current_user.id)
    end
  end

  def set_project_and_submissions
    @project = set_project
    @projects = set_projects
  end

  def set_projects
    Project.all_submissions(@lesson.id)
  end

  def set_project
    return unless user_signed_in?
    user_project || new_project
  end

  def user_project
    current_user.projects.where(lesson_id: @lesson.id).first
  end

  def new_project
    Project.new
  end

  def decorated_lesson
    LessonDecorator.new(lesson)
  end

  def lesson
    Lesson
      .includes(:section, course: [:lessons, sections: [:lessons]])
      .friendly
      .find(params[:id])
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper

  def next_lesson_button_state(lesson)
    if current_user&.has_completed?(lesson)
      'button--primary'
    else
      'button--secondary'
    end
  end
end

app/views/lessons/_index_submissions.html.erb
<% if projects.any? %>
  <% projects.each do |project| %>
    <div id="project-<%= project.id %>">
      <%= render 'project', project: ProjectDecorator.new(project) %>
    </div>
  <% end %>
<% else %>
  <h4 class="text-center accent">The project does not have any submissions yet</h4>
<% end %>

app/views/lessons/_lesson_buttons.html.erb
<%= link_to 'View Course',
    course_path(course.title_url, ref: 'lnav'),
    title: "Go back to '#{lesson.course.title}'",
    class: 'button button--secondary lesson-button-group__item lesson-button'
%>

<%= render 'lessons/lesson_completion_button', lesson: lesson, user: user %>

<% if lesson.next_lesson %>
  <%= link_to 'Next Lesson',
      course_lesson_path(course, lesson.next_lesson, ref: 'lnav'),
      title: "Move on to '#{lesson.next_lesson.title}'",
      class: "button #{next_lesson_button_state(lesson)} lesson-button-group__item lesson-button"
  %>
<% end %>

app/views/lessons/_lesson_completion_button.html.erb
<% if user_signed_in? %>
  <%= render 'lessons/lesson_completion_state', lesson: lesson, user: user %>
<% else %>
  <%= link_to 'Login to track progress',
      login_path,
      title: 'Go to login page',
      class: 'button button--primary lesson-button-group__item lesson-button' %>
<% end %>

app/views/lessons/_lesson_completion_state.html.erb
<% if lesson_completed?(user, lesson) %>
  <%= link_to lesson_completions_path(lesson), method: :delete, remote: true, class: 'button button--complete lesson-button-group__item lesson-button lesson-button--complete', title: 'Mark lesson incomplete' do %>
    <i class="lesson-button__icon far fa-check-circle" aria-hidden="true"></i>
  <% end %>
<% else %>
  <%= link_to lesson_completions_path(lesson), remote: true, method: :post, class: 'button button--primary lesson-button-group__item lesson-button', title: 'Mark lesson complete' do %>
    <i class="lesson-button__icon far fa-check-circle" aria-hidden="true"></i>Complete
  <% end %>
<% end %>

app/views/lessons/_new_submission.html.erb
<div class="row">
  <div class="col new-submission text-center mt-3 mb-3">
    <p class="new-submission__description">Share your solution!</p>

    <%= link_to 'Add your solution',
      '#',
      class: 'button button--primary add-submission-button',
      id: 'add-submission-button',
      data: { toggle: 'modal', target: '#project-submission-modal' }
    %>
  </div>
</div>

app/views/lessons/_recent_submissions.html.erb
<div class="container submissions-container">
  <div class="row">
    <div class="col submissions-container__header">
      <h4 class="submissions-container__title secondary bold">Solutions</h4>

      <% if projects.empty? %>
        <p class="submissions-container__instructions">This project has no solutions yet, be the first!</p>
      <% else %>
        <p class="submissions-container__instructions">
          Showing the most recent solutions. View the full list of solutions <%= link_to 'here', lesson_projects_path(lesson), class: 'projects-link accent', target: '_blank' %>
        </p>
      <% end %>
    </div>
  </div>

  <div id="new-submission">
    <%= render 'lessons/new_submission' if project&.new_record? %>
  </div>

  <% projects.each do |project| %>
    <div id="project-<%= project.id %>">
      <%= render 'projects/project', project: ProjectDecorator.new(project) %>
    </div>
  <% end %>
</div>

app/views/lessons/_viking-advert.html.erb
<div class="card-main viking-advert">
  <div class="viking-advert__header">
    <h2 class="viking-advert__pitch">Are you interested in accelerating your web development learning experience?</h2>
    <a href="https://www.thinkful.com/?utm_source=odin&utm_medium=cpc&utm_campaign=odin-homepage&utm_content=web-dev-3-icons" class="button button--primary">Get started</a>
  </div>
  <div class="viking-advert__body">
    <a href="https://www.thinkful.com/?utm_source=odin&utm_medium=cpc&utm_campaign=odin-homepage&utm_content=tf-logo" alt="Thinkful" class="viking-advert__brand-anchor">
        <div class="viking-advert__brand">
          <%= image_tag 'viking_advert/thinkful-logo.svg', alt: 'Thinkful Logo', class: 'viking-advert__logo' %>
          <h2 class="viking-advert__brand-name">Thinkful</h2>
        </div>
    </a>
    <ul class="viking-advert__icons-group">
      <li class="viking-advert__icons-group-item">
        <%= image_tag 'viking_advert/icon-calendar.svg', alt: '5-6 months', class: 'viking-advert__icon' %>
        <p class="viking-advert__icon-text">5-6 months</p>
      </li>

      <li class="viking-advert__icons-group-item">
        <%= image_tag 'viking_advert/icon-guarantee.svg', alt: 'Job Guarantee', class: 'viking-advert__icon' %>
        <p class="viking-advert__icon-text">Job Guarantee</p>
      </li>

      <li class="viking-advert__icons-group-item">
        <%= image_tag 'viking_advert/icon-mentor.svg', alt: '1-on-1 Mentorship', class: 'viking-advert__icon' %>
        <p class="viking-advert__icon-text">1-on-1 Mentorship</p>
      </li>
    </ul>
  </div>
</div>

app/views/lessons/show.html.erb
<%= title(@lesson.title) %>

<div class="container lesson">
  <div class="row">
    <div class="col-12">
      <div class="lesson-header">
        <%= link_to @lesson.course, class: 'course-card-header__link' do %>
          <%= render 'courses/course/banner', course: @lesson.course %>
        <% end %>
        <h2 class="lesson-header__title accent"><%= @lesson.title %></h2>
      </div>
    </div>

    <div class="col-lg-3">
      <div class="d-none d-lg-block d-xl-block lesson-navigation"></div>
    </div>

    <div class="col-lg-9">
      <div class="lesson-content">
        <%= @lesson.content.html_safe %>
      </div>
    </div>
  </div>
</div>

<div class="lesson-functions">
  <div class="container">
    <div class="card-main">
      <h1 class="lesson-functions__title">
        <%= @lesson.course.title %>
      </h1>

      <h3 class="lesson-functions__sub-title accent bold">
        <%= @lesson.title %>
      </h3>

      <div class="lesson-button-group">
        <%= render 'lesson_buttons', lesson: @lesson, course: @lesson.course, user: @user %>
      </div>

      <% if @projects && ProjectSubmissionFeature.enabled? %>
        <div id="submissions">
          <%= render 'recent_submissions',
            projects: @projects,
            project: @project,
            lesson: @lesson
          %>
        </div>
      <% end %>
    </div>

    <%= render 'shared/bottom_cta',
      button: chat_button,
      heading: 'Have a question?',
      sub_heading: 'Chat with our friendly Odin community in our Discord chatrooms!'
    %>

    <%= render 'viking-advert' %>
  </div>
</div>

<% if user_signed_in? %>
  <%= render 'projects/report_form_modal', lesson: @lesson %>
<% end %>

<% if user_signed_in? && @lesson.has_submission? %>
  <div id="project-submission-modal-wrapper">
    <%= render 'projects/form_modal', lesson: @lesson, project: @project %>
  </div>
<% end %>

<% if @project&.persisted? %>
  <%= render 'projects/delete_project_modal', lesson: @lesson, project: @project %>
<% end %>