config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  devise_for :users, controllers: {
    registrations: 'registrations',
    omniauth_callbacks: 'omniauth_callbacks',
  }

  devise_scope :user do
    get '/login' => 'devise/sessions#new'
    get '/logout' => 'devise/sessions#destroy', method: :delete
    get 'sign_up' => 'devise/registrations#new'
    get 'signup' => 'devise/registrations#new'
    get '/confirm_email' => 'users#send_confirmation_link'
  end

  namespace :api do
    resources :lesson_completions, only: [:index]
  end

  get 'home' => 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'faq' => 'static_pages#faq'
  get 'contributing' => 'static_pages#contributing'
  get 'terms_of_use' => 'static_pages#terms_of_use'
  get 'styleguide' => 'static_pages#style_guide'
  get 'success_stories' => 'static_pages#success_stories'
  get 'sitemap' => 'sitemap#index', defaults: { format: 'xml' }

  # failure route if github information returns invalid
  get '/auth/failure' => 'omniauth_callbacks#failure'
  resources :users, only: [:show, :update]

  namespace :users do
    resources :tracks, only: :create
  end
  get 'dashboard' => 'users#show', as: :dashboard

  # Deprecated Route to Introduction to Web Development from external links
  get '/courses/introduction-to-web-development' => redirect('/courses/web-development-101')

  resources :courses, only: %i(index show) do
    resources :lessons, only: :show
  end

  resources :lessons, only: :show do
    resources :projects, only: %i(index create update destroy) do
      resources :votes, only: %i(create)
      delete 'vote', to: 'votes#destroy'
    end

    resources :lesson_completions, only: %i(create), as: 'completions'
    delete 'lesson_completions' => 'lesson_completions#destroy', :as => 'lesson_completions'
  end

  resources :reports, only: :create

  match '/404' => 'errors#not_found', via: [ :get, :post, :patch, :delete ]

  # Explicitly redirect deprecated routes (301)
  get '/courses/curriculum' => redirect('/courses')
  get 'curriculum' => redirect('/courses')
  get 'scheduler' => redirect('/courses')

  resources :tracks, only: [:index, :show]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :redirect_if_logged_in, only: :home

  def home
  end

  def about
  end

  def faq
  end

  def terms_of_use
  end

  def style_guide
  end

  def success_stories
    @success_stories = SuccessStory.all
  end

  private

  def redirect_if_logged_in
    redirect_to dashboard_path if current_user
  end
end

app/views/static_pages/about/_belief.html.erb
<div class="row belief">
  <div class="col-sm-2 belief-illustration">
    <%= image_tag belief[:image_path], alt: belief[:image_alt], class: 'img-responsive' %>
  </div>

  <div class="col-sm-10 belief-description">
    <h3 class="belief-short-text">
      <strong>
        <%= belief[:short_text] %>
      </strong>
    </h3>
    <p>
      <%= belief[:description] %>
    </p>
  </div>
</div>

app/views/static_pages/about/_overview.html.erb
<section class="overview">
  <div class="container">
    <h2 class="overview__heading accent">Overview of The Odin Project</h2>

    <div class="row">

      <div class="col-12 col-md-4 col-lg-4">
        <div class="odin-stat card-main">
          <p class="odin-stat__content">80,000</p>
          <p>Learners</p>
        </div>
      </div>

      <div class="col-12 col-md-4 col-lg-4">
        <div class="odin-stat card-main">
          <p class="odin-stat__content">1500</p>
          <p>Contributors</p>
        </div>
      </div>

      <div class="col-12 col-md-4 col-lg-4">
        <div class="odin-stat card-main">
          <p class="odin-stat__content">2013</p>
          <p>Founded</p>
        </div>
      </div>
    </div>

    <div class="row">

      <div class="col-12 col-lg-8">
        <div class="card-main overview-card">
          <h3 class="overview-card__heading">Origin of The Odin Project</h3>
          <p class="overview-card__content">The Odin Project provides a free open source coding curriculum that can be taken entirely online. Since it’s inception, it has helped many students get hired as developers and has assisted countless others learn enough programming to work on their own personal projects.</p>
          <p class="overview-card__content">Founded in 2013 by Erik Trautman, The Odin Project is now sponsored by <a href="https://www.thinkful.com/?utm_source=odin&utm_medium=cpc&utm_campaign=odin-about" alt="Thinkful, a new type of technology school that provides 1-on-1 learning">Thinkful</a>, a new type of technology school that provides 1-on-1 learning through its network of industry experts, hiring partners, and online platform to deliver a structured and flexible education. The Odin Project is maintained and continually improved by a team of volunteers, many of whom learned to code with us.</p>
        </div>
      </div>

      <div class="col-12 col-lg-4">
        <div class=" card-main overview-card">
          <i class="fab fa-github fa-3x"></i>
          <h3 class="overview-card__heading overview-card__heading--inline">Open Source</h3>
          <p class="overview-card__content">This website and the curriculum it hosts are completely open source. That means anyone can work on new features or fix existing bugs on the website. This also extends to the curriculum itself, anyone can work on new lessons, add new resources and improve existing lessons.</p>
          <p class="overview-card__content">The Odin project would not be possible without the hard work of contributors from all across the world. If you're interested in helping us make Odin better please find out <a href="<%= contributing_path %>">how to contribute.</a></p>
        </div>
      </div>

    </div>
  </div>
</section>